[tool.poetry]
name = "iotemulator"
version = "0.1.0"
description = ""
authors = ["youtipie18 <youtipie@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiocoap = "^0.4.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
